# Incident fields
INC_INT_REF = 0
INC_SAFETY_NOTICE_REF = 2
INC_DATE = 5
REC_DATE = 6
ADDED_TO_AP_DATE = 7
ACTION_DATE = 9
DUE_DATE = 10
CLOSED_DATE = 13
ALERT_FORM = 14
INC_DESC = 15
CLIN_CONSEQ = 16
ACTIONS_TAKEN = 17
DECLARED_BY = 22
ISS_BY = 23

# Asset fields
ASSET_ID = 3
EQUIP_NO = 4
GMDN = 18
MANUFACTURE = 19
MODEL = 20
SERIAL =21